### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by Nuri1977** [Nuri1977/capstone-js-movies#19]
Choose images, text, icons, fonts.

**Comment by orozCoding** [comment]
We have decided to use the Poppins font:
https://fonts.google.com/specimen/Poppins

For the Icons, we are going to use Font Awesome.
https://fontawesome.com/

The text will come from the API.
https://www.tvmaze.com/api

The images will come from the API.
https://www.tvmaze.com/api
